create main page
vkarelina/vulpix-frontend pull request #1
Opened 2024-08-13 13:53 UTC by vkarelina

add main page

2024-08-14 06:44 UTC, s-skubedin requested changes

2024-08-14 06:44 UTC, s-skubedin commented on src/api/apiPost.ts
> +  return response;
const избыточна

2024-08-14 06:44 UTC, s-skubedin commented on src/components/Header/Header.tsx
> +  return (
Используй неявный return

2024-08-14 06:44 UTC, s-skubedin commented on src/components/PostCard/PostCard.tsx
> +            sx={{ color: "#fff" }}
Выноси в const

2024-08-14 06:44 UTC, s-skubedin commented on src/components/PostCard/PostCard.tsx
> +};
Стили выноси в отдельный файл

2024-08-14 06:44 UTC, s-skubedin commented on src/logo.tsx
Компоненты не должны находится в src директории, для этого есть components папка.
svg компоненты должна находится в соответствующей директории.
Либо используй svgr для рендера svg как компоненты

2024-08-14 06:44 UTC, s-skubedin commented on src/main.tsx
> +import store from "./redux/index.ts";
Нарушена сортировка

2024-08-14 06:44 UTC, s-skubedin commented on src/pages/main/MainPage.tsx
> +  const postsArr = useTypeSelector((state) => state.posts.posts);
useAppSelector

2024-08-14 06:44 UTC, s-skubedin commented on src/pages/main/MainPage.tsx
> +  const postsArr = useTypeSelector((state) => state.posts.posts);
posts - имеет множественное окончание. Значит posts - array, приписывать Arr - избыточно

2024-08-14 06:44 UTC, s-skubedin commented on src/redux/types/postType.ts
> +}
Типизация стора должна находится в файле со стором или на одном уровне с ним, а не в глобальных типах

2024-08-14 06:44 UTC, s-skubedin commented on src/redux/types/postType.ts
> +}
Экшены должны находиться в отдельно директории в соответстующем файле.
Экшены не должны быть enum

2024-08-14 06:44 UTC, s-skubedin commented on src/redux/types/postType.ts
> +}
Тип никак не связан с Post

2024-08-14 06:44 UTC, s-skubedin commented on src/redux/actions/actions.ts
Это action creators, а не action

2024-08-14 06:44 UTC, s-skubedin commented on src/redux/sagas/postSaga.ts
> +    const { data }: AxiosResponse<PostState[]> = yield call(fetchPostsApi);
Типизация избыточна

2024-08-14 11:58 UTC, vkarelina commented on src/redux/types/postType.ts
> +}
Привет. А есть какие-то причины с точки зрения производительности или читаемости в пользу использования строковых констант для экшенов вместо enum? Или всё взаимозаменяемо и зависит от кодстайла, принятого на проекте? Мне показалось удобным что я могу группировать экшены в зависимости от контекста.

2024-08-14 12:56 UTC, s-skubedin requested changes

2024-08-14 12:56 UTC, s-skubedin commented on src/components/Header/Header.tsx
> +import Logo from "../Logo/Logo";
Комопненты должны иметь index файл, который ре-экспортирует необходимые компоненты

2024-08-14 12:56 UTC, s-skubedin commented on src/api/apiPost.ts
> +  await api.get<Post[]>("/posts");
async/await - избыточно, лишнее создание события в очереди

2024-08-14 12:56 UTC, s-skubedin commented on src/components/PostCard/PostCardStyle.ts
> +  sx: { color: "#fff" },
Тут только sx надо выносить

2024-08-14 12:56 UTC, s-skubedin commented on src/main.tsx
> +import store from "./redux/index.ts";
Не исправлено

2024-08-14 12:56 UTC, s-skubedin commented on src/hooks/useTypeSelector.ts
> +export const useTypeSelector: TypedUseSelectorHook<RootState> =
useAppSelector

2024-08-14 12:56 UTC, s-skubedin commented on src/redux/actionsCreators/actionsPosts.ts
actionCreators

2024-08-14 12:56 UTC, s-skubedin commented on src/redux/types/postType.ts
> +}
enum - дополнительная обертка, + функция + доп данные в объекте.
Объект производительнее.
Бизнес-логика нарушена: enum - тип, а action types - это строки
Группировка - файлы

2024-08-15 11:31 UTC, s-skubedin approved these changes

2024-08-15 11:43 UTC, merged