add auth
vkarelina/vulpix-frontend pull request #2
Opened 2024-08-22 13:53 UTC by vkarelina

add auth reducer, saga and components

2024-08-22 14:23 UTC, n-krasnikov commented on src/components/AuthMenu/AuthMenu.tsx
> +  const [isOpenSignUp, setIsOpenSignUp] = useState(false);
Можно обойтись одним useState

2024-08-22 14:27 UTC, n-krasnikov commented on src/components/SignUpModal/SignUpModal.tsx
> +      <Box sx={{ width: 350, p: 4, bgcolor: "#111227" }}>
👀👀👀

2024-08-22 14:30 UTC, n-krasnikov commented on src/redux/actionsCreators/actionsCreatorsAuth.ts
> +export const fetchAccessToken = (payload: LoginData) => ({
Сделай единообразными AC
Либо payload, либо userData\error\....

2024-08-22 14:31 UTC, n-krasnikov commented on src/redux/reducers/authReducer.ts
> +  error?: string | null;
👀👀👀

2024-08-22 14:44 UTC, s-skubedin requested changes

2024-08-22 14:44 UTC, s-skubedin commented on src/api/api.ts
> +    if (token?.toString() !== "") {
token - уже строка, приводит к строке нет необходимости

2024-08-22 14:44 UTC, s-skubedin commented on src/components/AuthMenu/AuthMenu.tsx
> +  const [isOpenSignUp, setIsOpenSignUp] = useState(false);
<img width="293" alt="image" src="https://github.com/user-attachments/assets/09df0dae-e35e-4e6d-8e7f-58e1853d7c3a">

2024-08-22 14:44 UTC, s-skubedin commented on src/components/DropdownListUser/DropdownListUser.tsx
> +  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
Используй ref

2024-08-22 14:44 UTC, s-skubedin commented on src/components/Header/Header.tsx
> +      <AuthMenu user={user} />
user хранится в store, нет необходимости его прокидывать

2024-08-22 14:44 UTC, s-skubedin commented on src/components/Header/HeaderStyle.ts
> +    borderColor: "#dc5801d9",
Цвета выносите в палитру

2024-08-22 14:44 UTC, s-skubedin commented on src/components/SignUpModal/SignUpModal.tsx
> +      <Box sx={{ width: 350, p: 4, bgcolor: "#111227" }}>
<img width="205" alt="image" src="https://github.com/user-attachments/assets/105f3959-146e-442e-b7b9-aef7ea25baf2">

2024-08-22 14:44 UTC, s-skubedin commented on src/redux/actionsCreators/actionsCreatorsAuth.ts
Дублировать в имя папки в имени файле нет необходимости, только усложняет понимаение

2024-08-22 14:44 UTC, s-skubedin commented on src/redux/actionsCreators/actionsCreatorsAuth.ts
> +export const fetchAccessToken = (payload: LoginData) => ({
<img width="313" alt="image" src="https://github.com/user-attachments/assets/aea0d683-26f8-4e86-849a-4f222dc870f4">

2024-08-22 14:44 UTC, s-skubedin commented on src/redux/reducers/authReducer.ts
> +  error?: string | null;
<img width="269" alt="image" src="https://github.com/user-attachments/assets/326dc2d6-f196-414d-963d-2045445810d0">

2024-08-22 14:44 UTC, s-skubedin commented on src/redux/sagas/authSaga.ts
> +  }
Нет обработки иных ошибок

2024-08-23 07:48 UTC, vkarelina commented on src/components/DropdownListUser/DropdownListUser.tsx
> +  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);
Использовать только ref тут не получится, т.к от этого стейта зависит отрисовка выпадающего списка
![Снимок экрана 2024-08-23 104607](https://github.com/user-attachments/assets/95dd9d15-5be6-4874-b0f3-1658c7a57491)

2024-08-23 10:05 UTC, vkarelina commented on src/redux/sagas/authSaga.ts
> +  }
Каких именно ошибок? Все ошибки, которые приходят нам с бэка он отлавливает..

2024-08-23 13:28 UTC, s-skubedin approved these changes

2024-08-23 14:04 UTC, merged